version: "3.8"

services:
  ms-app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
